server:
  port: 8085

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9711

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8085/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
