server:
  port: 8083
  shutdown: graceful
  
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://zipkin-services:9711


i18nproperties:
  identifier: identifier
  name: name
  email: email

  identifiers:
    DE: Kennung
    EN: identifier
    ES: identificador

  names:
    DE: Name
    EN: name
    ES: nombre

  emails:
    DE: Email
    EN: email
    ES: Email

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-services:8085/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
