server:
  port: 8082
  shutdown: graceful

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://zipkin-services:9711

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    username: sa
    password: abc
    url: jdbc:h2:~/techbow/user/database/user;DB_CLOSE_ON_EXIT=FALSE

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-services:8085/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true