spring:
  application:
    name: discovery-service

  main:
    banner-mode: "off"

  output:
    ansi:
      enabled: "ALWAYS"

  config:
    import: optional:configserver:http://config-services:8084/
