server:
  port: 8084

spring:
  application:
    name: config-service

  cloud:
    config:
      label: docker
      server:
        git:
          uri: https://github.com/YuboC/Micro-Service/tree/docker
          search-paths: service-configs
          # defualt-label: docker
          # uri: ${HOME}/Developer/SpringCloud/user-start/service-configs

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-services:8085/eureka/
